language: python
python:
  - "3.11"

arch:
  - x86

branches:
  only:
    - main

install:
  - pip install poetry
  - poetry install

jobs:
  include:
    - stage: lint
      name: "Check Lint"
      script:
        - make check-lint
    - stage: test
      name: "Running Unit Tests"
      script:
        - make test

stages:
  - lint
  - test
