list molecules

add molecule CCC
list molecules
display molecule CCC
rename molecule CCC as ABC
list molecules
export molecule ABC as file
remove molecule ABC
list molecules

add molecule HHH
save molecule-set as foo
clear molecules
list molecules
load molecule-set foo
list molecules
list molecule-sets

clear molecules
add molecule BrBr
list molecules
display molecule BrBr
add toolkit rxn
set context rxn
predict reaction 'BrBr.c1ccc2cc3ccccc3cc2c1CCO'
enrich molecule-set with analysis
display molecule BrBr
clear analysis cache

create molecule CCCCCCC name test
list molecules

@ccc>>molecular_weight

load molecules using file 'base_molecules.sdf'
list molecules

export molecules
export molecules as 'test.csv'

show molecules using file 'base_molecules.sdf'
show molecules using file 'base_molecules.sdf' save as 'base_molecules-copy.sdf'
show mol 'CCC'