add toolkit ds4sd
set context ds4sd

search for similar molecules to 'C1(C(=C)C([O-])C1C)=O'
search for molecules in patents from list ['CN108473493B','US20190023713A1']
search for patents containing molecule 'CC(C)(c1ccccn1)C(CC(=O)O)Nc1nc(-c2c[nH]c3ncc(Cl)cc23)c(C#N)cc1F'
search for substructure instances of 'C1(C(=C)C([O-])C1C)=O' save as 'my_mol'

search collection 'patent-uspto' for '\"smiles#ccc(coc(=o)cs)(c(=o)c(=o)cs)c(=o)c(=o)cs\"' show (data)

display collection matches for 'Ibuprofen'
display collections in domains from list ['Scientific Literature']
display all collections
display collections for domain 'Business Insights'
display collection details 'Patents from USPTO'

