remove toolkit ds4sd
remove toolkit rxn
remove toolkit st4sd
remove toolkit gt4sd

ds4sd
ds4sd ?
rxn
rxn ?
st4sd
st4sd ?
gt4sd
gt4sd ?

list toolkits
list all toolkits

add toolkit ds4sd
add toolkit rxn
add toolkit st4sd
add toolkit gt4sd

ds4sd
ds4sd ?
rxn
rxn ?
st4sd
st4sd ?
gt4sd
gt4sd ?

list toolkits
list all toolkits

set context ds4sd
set context rxn
set context st4sd
set context gt4sd

get context
unset context